apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: operator-mariadb
    namespace: operators
    
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: operator-mariadb
  rules:
  - apiGroups:
    - 'mariadb.operator.flyover.com'
    resources:
    - databases
    - databaseusers
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - 'cd.ctl.io'
    resources:
    - cephvolumes
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ''
    - extensions
    - rbac.authorization.k8s.io
    resources:
    - namespaces
    - deployments
    - pods
    - services
    - secrets
    - serviceaccounts
    - roles
    - rolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: operator-mariadb
  roleRef:
    kind: ClusterRole
    name: operator-mariadb
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: operator-mariadb
    namespace: operators
          
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: databases.mariadb.operator.flyover.com
  spec:
    scope: Namespaced
    group: mariadb.operator.flyover.com
    version: v1
    names:
      kind: Database
      plural: databases
      singular: database
      shortNames: [ db ]
      
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: databaseusers.mariadb.operator.flyover.com
  spec:
    scope: Namespaced
    group: mariadb.operator.flyover.com
    version: v1
    names:
      kind: DatabaseUser
      plural: databaseusers
      singular: databaseuser
      shortNames: [ dbu ]
